package com.entity;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String mailbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.contacts
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.phone
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.address
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.profile
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String profile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date audit_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.username
     *
     * @return the value of company.username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.username
     *
     * @param username the value for company.username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.company_name
     *
     * @return the value of company.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.company_name
     *
     * @param company_name the value for company.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.mailbox
     *
     * @return the value of company.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.mailbox
     *
     * @param mailbox the value for company.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.password
     *
     * @return the value of company.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.password
     *
     * @param password the value for company.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.contacts
     *
     * @return the value of company.contacts
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.contacts
     *
     * @param contacts the value for company.contacts
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.phone
     *
     * @return the value of company.phone
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.phone
     *
     * @param phone the value for company.phone
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.address
     *
     * @return the value of company.address
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.address
     *
     * @param address the value for company.address
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.profile
     *
     * @return the value of company.profile
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.profile
     *
     * @param profile the value for company.profile
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.audit_date
     *
     * @return the value of company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getAudit_date() {
        return audit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.audit_date
     *
     * @param audit_date the value for company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAudit_date(Date audit_date) {
        this.audit_date = audit_date;
    }
}