package com.entity;

public class MailboxVerification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mailbox_verification.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String mailbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mailbox_verification.type
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mailbox_verification.verification_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String verification_code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mailbox_verification.mailbox
     *
     * @return the value of mailbox_verification.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mailbox_verification.mailbox
     *
     * @param mailbox the value for mailbox_verification.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mailbox_verification.type
     *
     * @return the value of mailbox_verification.type
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mailbox_verification.type
     *
     * @param type the value for mailbox_verification.type
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mailbox_verification.verification_code
     *
     * @return the value of mailbox_verification.verification_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getVerification_code() {
        return verification_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mailbox_verification.verification_code
     *
     * @param verification_code the value for mailbox_verification.verification_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setVerification_code(String verification_code) {
        this.verification_code = verification_code;
    }
}