package com.entity;

import java.util.Date;

public class NoticeCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.ID
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date release_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date audit_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_company.content
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.ID
     *
     * @return the value of notice_company.ID
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.ID
     *
     * @param ID the value for notice_company.ID
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.company_username
     *
     * @return the value of notice_company.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_username() {
        return company_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.company_username
     *
     * @param company_username the value for notice_company.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_username(String company_username) {
        this.company_username = company_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.release_date
     *
     * @return the value of notice_company.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getRelease_date() {
        return release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.release_date
     *
     * @param release_date the value for notice_company.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setRelease_date(Date release_date) {
        this.release_date = release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.audit_date
     *
     * @return the value of notice_company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getAudit_date() {
        return audit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.audit_date
     *
     * @param audit_date the value for notice_company.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAudit_date(Date audit_date) {
        this.audit_date = audit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.title
     *
     * @return the value of notice_company.title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.title
     *
     * @param title the value for notice_company.title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_company.content
     *
     * @return the value of notice_company.content
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_company.content
     *
     * @param content the value for notice_company.content
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}