package com.entity;

public class Professional {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String professional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column professional.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer orderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional.professional
     *
     * @return the value of professional.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional.professional
     *
     * @param professional the value for professional.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setProfessional(String professional) {
        this.professional = professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column professional.orderno
     *
     * @return the value of professional.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column professional.orderno
     *
     * @param orderno the value for professional.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }
}