package com.entity;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.introduction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.students_num
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer students_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.company_teacher
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.company_teacher_title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_teacher_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date release_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date audit_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.summary
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.major
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String major;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.No
     *
     * @return the value of project.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.No
     *
     * @param no the value for project.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.name
     *
     * @return the value of project.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.name
     *
     * @param name the value for project.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.introduction
     *
     * @return the value of project.introduction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.introduction
     *
     * @param introduction the value for project.introduction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.students_num
     *
     * @return the value of project.students_num
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getStudents_num() {
        return students_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.students_num
     *
     * @param students_num the value for project.students_num
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setStudents_num(Integer students_num) {
        this.students_num = students_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.company_username
     *
     * @return the value of project.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_username() {
        return company_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.company_username
     *
     * @param company_username the value for project.company_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_username(String company_username) {
        this.company_username = company_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.company_teacher
     *
     * @return the value of project.company_teacher
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_teacher() {
        return company_teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.company_teacher
     *
     * @param company_teacher the value for project.company_teacher
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_teacher(String company_teacher) {
        this.company_teacher = company_teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.company_teacher_title
     *
     * @return the value of project.company_teacher_title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_teacher_title() {
        return company_teacher_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.company_teacher_title
     *
     * @param company_teacher_title the value for project.company_teacher_title
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_teacher_title(String company_teacher_title) {
        this.company_teacher_title = company_teacher_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.release_date
     *
     * @return the value of project.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getRelease_date() {
        return release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.release_date
     *
     * @param release_date the value for project.release_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setRelease_date(Date release_date) {
        this.release_date = release_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.audit_date
     *
     * @return the value of project.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getAudit_date() {
        return audit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.audit_date
     *
     * @param audit_date the value for project.audit_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAudit_date(Date audit_date) {
        this.audit_date = audit_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.end_date
     *
     * @return the value of project.end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getEnd_date() {
        return end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.end_date
     *
     * @param end_date the value for project.end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setEnd_date(Date end_date) {
        this.end_date = end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.summary
     *
     * @return the value of project.summary
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.summary
     *
     * @param summary the value for project.summary
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.grade
     *
     * @return the value of project.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.grade
     *
     * @param grade the value for project.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.category
     *
     * @return the value of project.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.category
     *
     * @param category the value for project.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.major
     *
     * @return the value of project.major
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.major
     *
     * @param major the value for project.major
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setMajor(String major) {
        this.major = major;
    }
}