package com.entity;

public class ProjectCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_category.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_category.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer orderno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_category.category
     *
     * @return the value of project_category.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_category.category
     *
     * @param category the value for project_category.category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_category.orderno
     *
     * @return the value of project_category.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_category.orderno
     *
     * @param orderno the value for project_category.orderno
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }
}