package com.entity;

import java.util.Date;

public class ProjectSelect extends ProjectSelectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.sel_reason
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String sel_reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.company_sel_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date company_sel_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.score
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String company_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.sel_reason
     *
     * @return the value of project_select.sel_reason
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getSel_reason() {
        return sel_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.sel_reason
     *
     * @param sel_reason the value for project_select.sel_reason
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setSel_reason(String sel_reason) {
        this.sel_reason = sel_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.company_sel_date
     *
     * @return the value of project_select.company_sel_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getCompany_sel_date() {
        return company_sel_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.company_sel_date
     *
     * @param company_sel_date the value for project_select.company_sel_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_sel_date(Date company_sel_date) {
        this.company_sel_date = company_sel_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.score
     *
     * @return the value of project_select.score
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.score
     *
     * @param score the value for project_select.score
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.company_name
     *
     * @return the value of project_select.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.company_name
     *
     * @param company_name the value for project_select.company_name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }
}