package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNoIsNull() {
            addCriterion("No is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("No is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("No =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("No <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("No >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("No >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("No <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("No <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("No like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("No not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("No in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("No not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("No between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("No not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andStudents_numIsNull() {
            addCriterion("students_num is null");
            return (Criteria) this;
        }

        public Criteria andStudents_numIsNotNull() {
            addCriterion("students_num is not null");
            return (Criteria) this;
        }

        public Criteria andStudents_numEqualTo(Integer value) {
            addCriterion("students_num =", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numNotEqualTo(Integer value) {
            addCriterion("students_num <>", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numGreaterThan(Integer value) {
            addCriterion("students_num >", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numGreaterThanOrEqualTo(Integer value) {
            addCriterion("students_num >=", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numLessThan(Integer value) {
            addCriterion("students_num <", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numLessThanOrEqualTo(Integer value) {
            addCriterion("students_num <=", value, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numIn(List<Integer> values) {
            addCriterion("students_num in", values, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numNotIn(List<Integer> values) {
            addCriterion("students_num not in", values, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numBetween(Integer value1, Integer value2) {
            addCriterion("students_num between", value1, value2, "students_num");
            return (Criteria) this;
        }

        public Criteria andStudents_numNotBetween(Integer value1, Integer value2) {
            addCriterion("students_num not between", value1, value2, "students_num");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameIsNull() {
            addCriterion("company_username is null");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameIsNotNull() {
            addCriterion("company_username is not null");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameEqualTo(String value) {
            addCriterion("company_username =", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameNotEqualTo(String value) {
            addCriterion("company_username <>", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameGreaterThan(String value) {
            addCriterion("company_username >", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("company_username >=", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameLessThan(String value) {
            addCriterion("company_username <", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameLessThanOrEqualTo(String value) {
            addCriterion("company_username <=", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameLike(String value) {
            addCriterion("company_username like", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameNotLike(String value) {
            addCriterion("company_username not like", value, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameIn(List<String> values) {
            addCriterion("company_username in", values, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameNotIn(List<String> values) {
            addCriterion("company_username not in", values, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameBetween(String value1, String value2) {
            addCriterion("company_username between", value1, value2, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_usernameNotBetween(String value1, String value2) {
            addCriterion("company_username not between", value1, value2, "company_username");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherIsNull() {
            addCriterion("company_teacher is null");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherIsNotNull() {
            addCriterion("company_teacher is not null");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherEqualTo(String value) {
            addCriterion("company_teacher =", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherNotEqualTo(String value) {
            addCriterion("company_teacher <>", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherGreaterThan(String value) {
            addCriterion("company_teacher >", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherGreaterThanOrEqualTo(String value) {
            addCriterion("company_teacher >=", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherLessThan(String value) {
            addCriterion("company_teacher <", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherLessThanOrEqualTo(String value) {
            addCriterion("company_teacher <=", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherLike(String value) {
            addCriterion("company_teacher like", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherNotLike(String value) {
            addCriterion("company_teacher not like", value, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherIn(List<String> values) {
            addCriterion("company_teacher in", values, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherNotIn(List<String> values) {
            addCriterion("company_teacher not in", values, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherBetween(String value1, String value2) {
            addCriterion("company_teacher between", value1, value2, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacherNotBetween(String value1, String value2) {
            addCriterion("company_teacher not between", value1, value2, "company_teacher");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleIsNull() {
            addCriterion("company_teacher_title is null");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleIsNotNull() {
            addCriterion("company_teacher_title is not null");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleEqualTo(String value) {
            addCriterion("company_teacher_title =", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleNotEqualTo(String value) {
            addCriterion("company_teacher_title <>", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleGreaterThan(String value) {
            addCriterion("company_teacher_title >", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleGreaterThanOrEqualTo(String value) {
            addCriterion("company_teacher_title >=", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleLessThan(String value) {
            addCriterion("company_teacher_title <", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleLessThanOrEqualTo(String value) {
            addCriterion("company_teacher_title <=", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleLike(String value) {
            addCriterion("company_teacher_title like", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleNotLike(String value) {
            addCriterion("company_teacher_title not like", value, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleIn(List<String> values) {
            addCriterion("company_teacher_title in", values, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleNotIn(List<String> values) {
            addCriterion("company_teacher_title not in", values, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleBetween(String value1, String value2) {
            addCriterion("company_teacher_title between", value1, value2, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andCompany_teacher_titleNotBetween(String value1, String value2) {
            addCriterion("company_teacher_title not between", value1, value2, "company_teacher_title");
            return (Criteria) this;
        }

        public Criteria andRelease_dateIsNull() {
            addCriterion("release_date is null");
            return (Criteria) this;
        }

        public Criteria andRelease_dateIsNotNull() {
            addCriterion("release_date is not null");
            return (Criteria) this;
        }

        public Criteria andRelease_dateEqualTo(Date value) {
            addCriterion("release_date =", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateNotEqualTo(Date value) {
            addCriterion("release_date <>", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateGreaterThan(Date value) {
            addCriterion("release_date >", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("release_date >=", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateLessThan(Date value) {
            addCriterion("release_date <", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateLessThanOrEqualTo(Date value) {
            addCriterion("release_date <=", value, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateIn(List<Date> values) {
            addCriterion("release_date in", values, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateNotIn(List<Date> values) {
            addCriterion("release_date not in", values, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateBetween(Date value1, Date value2) {
            addCriterion("release_date between", value1, value2, "release_date");
            return (Criteria) this;
        }

        public Criteria andRelease_dateNotBetween(Date value1, Date value2) {
            addCriterion("release_date not between", value1, value2, "release_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateIsNull() {
            addCriterion("audit_date is null");
            return (Criteria) this;
        }

        public Criteria andAudit_dateIsNotNull() {
            addCriterion("audit_date is not null");
            return (Criteria) this;
        }

        public Criteria andAudit_dateEqualTo(Date value) {
            addCriterion("audit_date =", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateNotEqualTo(Date value) {
            addCriterion("audit_date <>", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateGreaterThan(Date value) {
            addCriterion("audit_date >", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_date >=", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateLessThan(Date value) {
            addCriterion("audit_date <", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateLessThanOrEqualTo(Date value) {
            addCriterion("audit_date <=", value, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateIn(List<Date> values) {
            addCriterion("audit_date in", values, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateNotIn(List<Date> values) {
            addCriterion("audit_date not in", values, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateBetween(Date value1, Date value2) {
            addCriterion("audit_date between", value1, value2, "audit_date");
            return (Criteria) this;
        }

        public Criteria andAudit_dateNotBetween(Date value1, Date value2) {
            addCriterion("audit_date not between", value1, value2, "audit_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEnd_dateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEnd_dateEqualTo(Date value) {
            addCriterion("end_date =", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateNotEqualTo(Date value) {
            addCriterion("end_date <>", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateGreaterThan(Date value) {
            addCriterion("end_date >", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("end_date >=", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateLessThan(Date value) {
            addCriterion("end_date <", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateLessThanOrEqualTo(Date value) {
            addCriterion("end_date <=", value, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateIn(List<Date> values) {
            addCriterion("end_date in", values, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateNotIn(List<Date> values) {
            addCriterion("end_date not in", values, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateBetween(Date value1, Date value2) {
            addCriterion("end_date between", value1, value2, "end_date");
            return (Criteria) this;
        }

        public Criteria andEnd_dateNotBetween(Date value1, Date value2) {
            addCriterion("end_date not between", value1, value2, "end_date");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNull() {
            addCriterion("summary is null");
            return (Criteria) this;
        }

        public Criteria andSummaryIsNotNull() {
            addCriterion("summary is not null");
            return (Criteria) this;
        }

        public Criteria andSummaryEqualTo(String value) {
            addCriterion("summary =", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotEqualTo(String value) {
            addCriterion("summary <>", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThan(String value) {
            addCriterion("summary >", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryGreaterThanOrEqualTo(String value) {
            addCriterion("summary >=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThan(String value) {
            addCriterion("summary <", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLessThanOrEqualTo(String value) {
            addCriterion("summary <=", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryLike(String value) {
            addCriterion("summary like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotLike(String value) {
            addCriterion("summary not like", value, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryIn(List<String> values) {
            addCriterion("summary in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotIn(List<String> values) {
            addCriterion("summary not in", values, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryBetween(String value1, String value2) {
            addCriterion("summary between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andSummaryNotBetween(String value1, String value2) {
            addCriterion("summary not between", value1, value2, "summary");
            return (Criteria) this;
        }

        public Criteria andGradeIsNull() {
            addCriterion("grade is null");
            return (Criteria) this;
        }

        public Criteria andGradeIsNotNull() {
            addCriterion("grade is not null");
            return (Criteria) this;
        }

        public Criteria andGradeEqualTo(Integer value) {
            addCriterion("grade =", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotEqualTo(Integer value) {
            addCriterion("grade <>", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThan(Integer value) {
            addCriterion("grade >", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("grade >=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThan(Integer value) {
            addCriterion("grade <", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeLessThanOrEqualTo(Integer value) {
            addCriterion("grade <=", value, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeIn(List<Integer> values) {
            addCriterion("grade in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotIn(List<Integer> values) {
            addCriterion("grade not in", values, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeBetween(Integer value1, Integer value2) {
            addCriterion("grade between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("grade not between", value1, value2, "grade");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNull() {
            addCriterion("category is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIsNotNull() {
            addCriterion("category is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryEqualTo(String value) {
            addCriterion("category =", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotEqualTo(String value) {
            addCriterion("category <>", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThan(String value) {
            addCriterion("category >", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("category >=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThan(String value) {
            addCriterion("category <", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLessThanOrEqualTo(String value) {
            addCriterion("category <=", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryLike(String value) {
            addCriterion("category like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotLike(String value) {
            addCriterion("category not like", value, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryIn(List<String> values) {
            addCriterion("category in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotIn(List<String> values) {
            addCriterion("category not in", values, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryBetween(String value1, String value2) {
            addCriterion("category between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andCategoryNotBetween(String value1, String value2) {
            addCriterion("category not between", value1, value2, "category");
            return (Criteria) this;
        }

        public Criteria andMajorIsNull() {
            addCriterion("major is null");
            return (Criteria) this;
        }

        public Criteria andMajorIsNotNull() {
            addCriterion("major is not null");
            return (Criteria) this;
        }

        public Criteria andMajorEqualTo(String value) {
            addCriterion("major =", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotEqualTo(String value) {
            addCriterion("major <>", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThan(String value) {
            addCriterion("major >", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorGreaterThanOrEqualTo(String value) {
            addCriterion("major >=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThan(String value) {
            addCriterion("major <", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLessThanOrEqualTo(String value) {
            addCriterion("major <=", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorLike(String value) {
            addCriterion("major like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotLike(String value) {
            addCriterion("major not like", value, "major");
            return (Criteria) this;
        }

        public Criteria andMajorIn(List<String> values) {
            addCriterion("major in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotIn(List<String> values) {
            addCriterion("major not in", values, "major");
            return (Criteria) this;
        }

        public Criteria andMajorBetween(String value1, String value2) {
            addCriterion("major between", value1, value2, "major");
            return (Criteria) this;
        }

        public Criteria andMajorNotBetween(String value1, String value2) {
            addCriterion("major not between", value1, value2, "major");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 10 16:29:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}