package com.entity;

public class ProjectSelectKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.studentNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String studentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_select.projectNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String projectNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.studentNo
     *
     * @return the value of project_select.studentNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getStudentNo() {
        return studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.studentNo
     *
     * @param studentNo the value for project_select.studentNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setStudentNo(String studentNo) {
        this.studentNo = studentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_select.projectNo
     *
     * @return the value of project_select.projectNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_select.projectNo
     *
     * @param projectNo the value for project_select.projectNo
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo;
    }
}