package com.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.level
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String professional;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classs
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String classs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String mailbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.subject_background
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String subject_background;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.learning_experience
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String learning_experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.research_direction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String research_direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.No
     *
     * @return the value of student.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.No
     *
     * @param no the value for student.No
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.level
     *
     * @return the value of student.level
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.level
     *
     * @param level the value for student.level
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.professional
     *
     * @return the value of student.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getProfessional() {
        return professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.professional
     *
     * @param professional the value for student.professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setProfessional(String professional) {
        this.professional = professional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classs
     *
     * @return the value of student.classs
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getClasss() {
        return classs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classs
     *
     * @param classs the value for student.classs
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setClasss(String classs) {
        this.classs = classs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.password
     *
     * @return the value of student.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.password
     *
     * @param password the value for student.password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.mailbox
     *
     * @return the value of student.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getMailbox() {
        return mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.mailbox
     *
     * @param mailbox the value for student.mailbox
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setMailbox(String mailbox) {
        this.mailbox = mailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.subject_background
     *
     * @return the value of student.subject_background
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getSubject_background() {
        return subject_background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.subject_background
     *
     * @param subject_background the value for student.subject_background
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setSubject_background(String subject_background) {
        this.subject_background = subject_background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.learning_experience
     *
     * @return the value of student.learning_experience
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getLearning_experience() {
        return learning_experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.learning_experience
     *
     * @param learning_experience the value for student.learning_experience
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setLearning_experience(String learning_experience) {
        this.learning_experience = learning_experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.research_direction
     *
     * @return the value of student.research_direction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getResearch_direction() {
        return research_direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.research_direction
     *
     * @param research_direction the value for student.research_direction
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setResearch_direction(String research_direction) {
        this.research_direction = research_direction;
    }
}