package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SystemParameterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public SystemParameterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAdmin_usernameIsNull() {
            addCriterion("admin_username is null");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameIsNotNull() {
            addCriterion("admin_username is not null");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameEqualTo(String value) {
            addCriterion("admin_username =", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameNotEqualTo(String value) {
            addCriterion("admin_username <>", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameGreaterThan(String value) {
            addCriterion("admin_username >", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameGreaterThanOrEqualTo(String value) {
            addCriterion("admin_username >=", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameLessThan(String value) {
            addCriterion("admin_username <", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameLessThanOrEqualTo(String value) {
            addCriterion("admin_username <=", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameLike(String value) {
            addCriterion("admin_username like", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameNotLike(String value) {
            addCriterion("admin_username not like", value, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameIn(List<String> values) {
            addCriterion("admin_username in", values, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameNotIn(List<String> values) {
            addCriterion("admin_username not in", values, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameBetween(String value1, String value2) {
            addCriterion("admin_username between", value1, value2, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_usernameNotBetween(String value1, String value2) {
            addCriterion("admin_username not between", value1, value2, "admin_username");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordIsNull() {
            addCriterion("admin_password is null");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordIsNotNull() {
            addCriterion("admin_password is not null");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordEqualTo(String value) {
            addCriterion("admin_password =", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordNotEqualTo(String value) {
            addCriterion("admin_password <>", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordGreaterThan(String value) {
            addCriterion("admin_password >", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordGreaterThanOrEqualTo(String value) {
            addCriterion("admin_password >=", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordLessThan(String value) {
            addCriterion("admin_password <", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordLessThanOrEqualTo(String value) {
            addCriterion("admin_password <=", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordLike(String value) {
            addCriterion("admin_password like", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordNotLike(String value) {
            addCriterion("admin_password not like", value, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordIn(List<String> values) {
            addCriterion("admin_password in", values, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordNotIn(List<String> values) {
            addCriterion("admin_password not in", values, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordBetween(String value1, String value2) {
            addCriterion("admin_password between", value1, value2, "admin_password");
            return (Criteria) this;
        }

        public Criteria andAdmin_passwordNotBetween(String value1, String value2) {
            addCriterion("admin_password not between", value1, value2, "admin_password");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIsNull() {
            addCriterion("invitation_code is null");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIsNotNull() {
            addCriterion("invitation_code is not null");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeEqualTo(String value) {
            addCriterion("invitation_code =", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotEqualTo(String value) {
            addCriterion("invitation_code <>", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeGreaterThan(String value) {
            addCriterion("invitation_code >", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeGreaterThanOrEqualTo(String value) {
            addCriterion("invitation_code >=", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLessThan(String value) {
            addCriterion("invitation_code <", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLessThanOrEqualTo(String value) {
            addCriterion("invitation_code <=", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeLike(String value) {
            addCriterion("invitation_code like", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotLike(String value) {
            addCriterion("invitation_code not like", value, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeIn(List<String> values) {
            addCriterion("invitation_code in", values, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotIn(List<String> values) {
            addCriterion("invitation_code not in", values, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeBetween(String value1, String value2) {
            addCriterion("invitation_code between", value1, value2, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andInvitation_codeNotBetween(String value1, String value2) {
            addCriterion("invitation_code not between", value1, value2, "invitation_code");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateIsNull() {
            addCriterion("release_project_start_date is null");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateIsNotNull() {
            addCriterion("release_project_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateEqualTo(Date value) {
            addCriterion("release_project_start_date =", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateNotEqualTo(Date value) {
            addCriterion("release_project_start_date <>", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateGreaterThan(Date value) {
            addCriterion("release_project_start_date >", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("release_project_start_date >=", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateLessThan(Date value) {
            addCriterion("release_project_start_date <", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateLessThanOrEqualTo(Date value) {
            addCriterion("release_project_start_date <=", value, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateIn(List<Date> values) {
            addCriterion("release_project_start_date in", values, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateNotIn(List<Date> values) {
            addCriterion("release_project_start_date not in", values, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateBetween(Date value1, Date value2) {
            addCriterion("release_project_start_date between", value1, value2, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_start_dateNotBetween(Date value1, Date value2) {
            addCriterion("release_project_start_date not between", value1, value2, "release_project_start_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateIsNull() {
            addCriterion("release_project_end_date is null");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateIsNotNull() {
            addCriterion("release_project_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateEqualTo(Date value) {
            addCriterion("release_project_end_date =", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateNotEqualTo(Date value) {
            addCriterion("release_project_end_date <>", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateGreaterThan(Date value) {
            addCriterion("release_project_end_date >", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("release_project_end_date >=", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateLessThan(Date value) {
            addCriterion("release_project_end_date <", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateLessThanOrEqualTo(Date value) {
            addCriterion("release_project_end_date <=", value, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateIn(List<Date> values) {
            addCriterion("release_project_end_date in", values, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateNotIn(List<Date> values) {
            addCriterion("release_project_end_date not in", values, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateBetween(Date value1, Date value2) {
            addCriterion("release_project_end_date between", value1, value2, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andRelease_project_end_dateNotBetween(Date value1, Date value2) {
            addCriterion("release_project_end_date not between", value1, value2, "release_project_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateIsNull() {
            addCriterion("student_sel_start_date is null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateIsNotNull() {
            addCriterion("student_sel_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateEqualTo(Date value) {
            addCriterion("student_sel_start_date =", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateNotEqualTo(Date value) {
            addCriterion("student_sel_start_date <>", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateGreaterThan(Date value) {
            addCriterion("student_sel_start_date >", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("student_sel_start_date >=", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateLessThan(Date value) {
            addCriterion("student_sel_start_date <", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateLessThanOrEqualTo(Date value) {
            addCriterion("student_sel_start_date <=", value, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateIn(List<Date> values) {
            addCriterion("student_sel_start_date in", values, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateNotIn(List<Date> values) {
            addCriterion("student_sel_start_date not in", values, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateBetween(Date value1, Date value2) {
            addCriterion("student_sel_start_date between", value1, value2, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_start_dateNotBetween(Date value1, Date value2) {
            addCriterion("student_sel_start_date not between", value1, value2, "student_sel_start_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateIsNull() {
            addCriterion("student_sel_end_date is null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateIsNotNull() {
            addCriterion("student_sel_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateEqualTo(Date value) {
            addCriterion("student_sel_end_date =", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateNotEqualTo(Date value) {
            addCriterion("student_sel_end_date <>", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateGreaterThan(Date value) {
            addCriterion("student_sel_end_date >", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("student_sel_end_date >=", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateLessThan(Date value) {
            addCriterion("student_sel_end_date <", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateLessThanOrEqualTo(Date value) {
            addCriterion("student_sel_end_date <=", value, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateIn(List<Date> values) {
            addCriterion("student_sel_end_date in", values, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateNotIn(List<Date> values) {
            addCriterion("student_sel_end_date not in", values, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateBetween(Date value1, Date value2) {
            addCriterion("student_sel_end_date between", value1, value2, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_end_dateNotBetween(Date value1, Date value2) {
            addCriterion("student_sel_end_date not between", value1, value2, "student_sel_end_date");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumIsNull() {
            addCriterion("student_sel_maxnum is null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumIsNotNull() {
            addCriterion("student_sel_maxnum is not null");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumEqualTo(Integer value) {
            addCriterion("student_sel_maxnum =", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumNotEqualTo(Integer value) {
            addCriterion("student_sel_maxnum <>", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumGreaterThan(Integer value) {
            addCriterion("student_sel_maxnum >", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_sel_maxnum >=", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumLessThan(Integer value) {
            addCriterion("student_sel_maxnum <", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumLessThanOrEqualTo(Integer value) {
            addCriterion("student_sel_maxnum <=", value, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumIn(List<Integer> values) {
            addCriterion("student_sel_maxnum in", values, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumNotIn(List<Integer> values) {
            addCriterion("student_sel_maxnum not in", values, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumBetween(Integer value1, Integer value2) {
            addCriterion("student_sel_maxnum between", value1, value2, "student_sel_maxnum");
            return (Criteria) this;
        }

        public Criteria andStudent_sel_maxnumNotBetween(Integer value1, Integer value2) {
            addCriterion("student_sel_maxnum not between", value1, value2, "student_sel_maxnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_parameter
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 10 16:29:23 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table system_parameter
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}