package com.entity;

import java.util.Date;

public class SystemParameter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.admin_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String admin_username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.admin_password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String admin_password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.invitation_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private String invitation_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.release_project_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date release_project_start_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.release_project_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date release_project_end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.student_sel_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date student_sel_start_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.student_sel_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Date student_sel_end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_parameter.student_sel_maxnum
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    private Integer student_sel_maxnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.admin_username
     *
     * @return the value of system_parameter.admin_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getAdmin_username() {
        return admin_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.admin_username
     *
     * @param admin_username the value for system_parameter.admin_username
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAdmin_username(String admin_username) {
        this.admin_username = admin_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.admin_password
     *
     * @return the value of system_parameter.admin_password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getAdmin_password() {
        return admin_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.admin_password
     *
     * @param admin_password the value for system_parameter.admin_password
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setAdmin_password(String admin_password) {
        this.admin_password = admin_password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.invitation_code
     *
     * @return the value of system_parameter.invitation_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public String getInvitation_code() {
        return invitation_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.invitation_code
     *
     * @param invitation_code the value for system_parameter.invitation_code
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setInvitation_code(String invitation_code) {
        this.invitation_code = invitation_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.release_project_start_date
     *
     * @return the value of system_parameter.release_project_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getRelease_project_start_date() {
        return release_project_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.release_project_start_date
     *
     * @param release_project_start_date the value for system_parameter.release_project_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setRelease_project_start_date(Date release_project_start_date) {
        this.release_project_start_date = release_project_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.release_project_end_date
     *
     * @return the value of system_parameter.release_project_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getRelease_project_end_date() {
        return release_project_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.release_project_end_date
     *
     * @param release_project_end_date the value for system_parameter.release_project_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setRelease_project_end_date(Date release_project_end_date) {
        this.release_project_end_date = release_project_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.student_sel_start_date
     *
     * @return the value of system_parameter.student_sel_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getStudent_sel_start_date() {
        return student_sel_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.student_sel_start_date
     *
     * @param student_sel_start_date the value for system_parameter.student_sel_start_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setStudent_sel_start_date(Date student_sel_start_date) {
        this.student_sel_start_date = student_sel_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.student_sel_end_date
     *
     * @return the value of system_parameter.student_sel_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Date getStudent_sel_end_date() {
        return student_sel_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.student_sel_end_date
     *
     * @param student_sel_end_date the value for system_parameter.student_sel_end_date
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setStudent_sel_end_date(Date student_sel_end_date) {
        this.student_sel_end_date = student_sel_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_parameter.student_sel_maxnum
     *
     * @return the value of system_parameter.student_sel_maxnum
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public Integer getStudent_sel_maxnum() {
        return student_sel_maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_parameter.student_sel_maxnum
     *
     * @param student_sel_maxnum the value for system_parameter.student_sel_maxnum
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    public void setStudent_sel_maxnum(Integer student_sel_maxnum) {
        this.student_sel_maxnum = student_sel_maxnum;
    }
}