package com.dao;

import com.entity.MailboxVerification;
import com.entity.MailboxVerificationExample;
import java.util.List;

public interface MailboxVerificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(String mailbox);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(MailboxVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(MailboxVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<MailboxVerification> selectByExample(MailboxVerificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    MailboxVerification selectByPrimaryKey(String mailbox);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(MailboxVerification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailbox_verification
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(MailboxVerification record);
}