package com.dao;

import com.entity.NoticeAdmin;
import com.entity.NoticeAdminExample;
import java.util.List;

public interface NoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<NoticeAdmin> selectByExample(NoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    NoticeAdmin selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(NoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_admin
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(NoticeAdmin record);

    List<NoticeAdmin> findAllNoticeAdmin();
}