package com.dao;

import com.entity.NoticeCompany;
import com.entity.NoticeCompanyExample;
import java.util.List;

public interface NoticeCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(NoticeCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(NoticeCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<NoticeCompany> selectByExample(NoticeCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    NoticeCompany selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(NoticeCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_company
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(NoticeCompany record);
}