package com.dao;

import com.entity.Professional;
import com.entity.ProfessionalExample;
import java.util.List;

public interface ProfessionalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(String professional);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(Professional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(Professional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<Professional> selectByExample(ProfessionalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    Professional selectByPrimaryKey(String professional);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(Professional record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table professional
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(Professional record);
}