package com.dao;

import com.entity.ProjectCategory;
import com.entity.ProjectCategoryExample;
import java.util.List;

public interface ProjectCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(String category);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(ProjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(ProjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<ProjectCategory> selectByExample(ProjectCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    ProjectCategory selectByPrimaryKey(String category);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_category
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(ProjectCategory record);
}