package com.dao;

import com.entity.Project;
import com.entity.ProjectExample;
import java.util.List;

import com.github.pagehelper.Page;


public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    Project selectByPrimaryKey(String no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(Project record);



    List<Project> findByPage(Project project);

    List<Project> findByNoaduitProjectList(Project project);

    List<Project> findByCompany_username(Project project);


    List<Project> findAllProject();

    void updateauditdate(String no);

    List<Project> findByname(Project project);


    List<Project> selectProjectByStu(String stu_no);

    List<Project> findProjectByStuNo(String stuNo);

    List<Project> findAllProjectByThree(String stu_no,String name, String price, Integer typeId);
    Project findCompany_name(String projectId);

}