package com.dao;

import com.entity.ProjectSelect;
import com.entity.ProjectSelectExample;
import com.entity.ProjectSelectKey;
import java.util.List;

public interface ProjectSelectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int deleteByPrimaryKey(ProjectSelectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insert(ProjectSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int insertSelective(ProjectSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    List<ProjectSelect> selectByExample(ProjectSelectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    ProjectSelect selectByPrimaryKey(ProjectSelectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectSelect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_select
     *
     * @mbg.generated Tue Sep 10 16:29:23 CST 2019
     */
    int updateByPrimaryKey(ProjectSelect record);


    List<ProjectSelect> findProjectScore(String company_name);

    List<ProjectSelect> findProjectScoreSome(ProjectSelect projectSelect);

    ProjectSelect findProjectScoreById(String no);

    void deleteProjectSelectss(String no);

    List<ProjectSelect> findAllScore(String stu_no);
    List<ProjectSelect> findScore(String stu_no,int typeId);

    void deleProjectByProjectNo(String projectNo,String stu_no);


    void insertProjectIntoSelect(String stu_no, String projectId, String sel_reason, String company_name);

    ProjectSelect findStuProjectTure(String stu_no, String projectId);
}